config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users, :controllers => { :sessions => "users/sessions",
  registrations: 'users/registrations'}

  root to: 'movies#index'
  
  resources :movies, only: [:index, :show] do
    resources :ratings, only: [:create]
  end
   resources :user_reviews, only: [:index, :edit, :update, :destroy]
end

 

app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_reviews = current_user.ratings
    # render json: @user_reviews
  end

  def edit
    @rating = set_ratings
      # render json: RatingSerializer.new(@rating)
  end

  def update
    @rating = set_ratings
    if @rating.update(review_params)
      redirect_to user_reviews_path, notice: 'Review updated successfully.'
      #  render json:{
      #   message: "updated successfully",
      #   rating: RatingSerializer.new(@rating)
      # } 
      
    else
      render :edit
      # render json: {errors: "rating not found"}
x   end
  end

  def destroy
    @rating = set_ratings
    @rating.destroy
    redirect_to user_reviews_path, alert: 'Review deleted successfully.'
    # render json: {message:"review deleted successfully"}
  end

  private

  def review_params
    params.require(:rating).permit(:score, :review)
  end

  def set_ratings
     @rating = current_user.ratings.find(params[:id])
  end
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/views/user_reviews/edit.html.erb
<style>
  .movie-title {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .rating-form {
    margin-top: 20px;
  }

  .rating-form .field {
    margin-bottom: 10px;
  }

  .rating-form label {
    display: block;
    font-weight: bold;
  }

  .rating-form select {
    width: 100px;
  }

  .rating-form textarea {
    width: 300px;
    height: 100px;
  }

  .rating-form .actions {
    margin-top: 10px;
  }

</style>

<h1 class="movie-title"><h1>Edit Review</h1>
</h1>

<% if user_signed_in? %>
  <div class="rating-form">
    <%= form_with(model: @rating, url: user_review_path(@rating.id), method: :patch) do |form| %>
      <div class="field">
        <%= form.label :score %>
        <%= form.select :score, (1..5),selected: @rating.score %>
      </div>
      <div class="field">
        <%= form.label :review %>
        <%= form.text_area :review %>
      </div>
      <div class="actions">
    <%= form.submit 'Update Review' %>
  
    <% end %>
  <%= link_to 'Cancel', user_reviews_path %>
  </div>


<% end %>

app/views/user_reviews/index.html.erb
<style>
  .user-reviews-table {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
  }

  .movie {
    background-color: lightgoldenrodyellow;
    padding: 10px;
    margin-bottom: 20px;
    border-radius: 10px;
  }

  .movie h2 {
    font-size: 15px;
    margin-bottom: 5px;
    text-decoration: none;
  }

  .movie h3 {
    font-size: 25px;
    margin-top: 10px;
    margin-bottom: 10px;
  }
  .movie p {
    font-size: 20px;
    color: black;
    margin-bottom: 2px;
    margin-top: 10px
  }

  .star-icon {
    vertical-align: middle;
    margin-left: 3px;
  height: 15px; 
  width: 15px; 
  margin-bottom: 5px;
  }

  .rating-container {
  display: flex;
  align-items: center;
  gap: 500px;
}

.edit-delete-links {
  font-size: 20px;
  display: flex;
  gap: 10px;
  margin-top: 10px;
}
</style>

<div class="user-reviews-table">
  <h1>My Reviews</h1>  


<div class="review-list">
   <% @user_reviews.each do |rating| %>
    <div class="movie">
      <h2><%= rating.movie.title.upcase%></h2>
      <h3><%= rating.review %></h3>
      <div class="rating-container">
  <p>Your Rating: <%= rating.score %><%= image_tag('star.png', alt: 'Star', class: 'star-icon')%></p>
  <div class="edit-delete-links">
    <%= link_to 'Edit', edit_user_review_path(rating) %>
    <%= button_to 'Delete', user_review_path(rating), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>
    </div>
  <% end %>
</div>


  <div style="position: absolute; top: 10px; left: 100px;">
    <%= link_to 'Back', movies_path, class: 'back-button' %>
  </div>
  </div>